
# 注释符
#todo makefile 函数

#foo = $(bar)
#bar = $(ugh)
#ugh = Huh?

#x := foo
#y := $(x) bar
#x := later

#foo := a.o b.o c.o
#bar := $(foo:.o=.c)

dir = foo
sources := $(wildcard $(dir)/*.c)

all:
	@echo $(sources)
