######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 27 20:20:38 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += closelab2.cpp
