######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 28 14:23:39 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mytime.h
SOURCES += main.cpp mytime.cpp
