######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 3 15:21:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += closelab.cpp
