######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 29 14:57:08 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h
SOURCES += adder.cpp testadder.cpp
