######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 27 21:16:43 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += lianxi.cpp
