######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 18 17:46:57 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dmsclient.h mythread.h ../logreader.h ../data.h ../logsender.h
SOURCES += dmsclient.cpp \
           mythread.cpp \
           testdmsclient.cpp \
           ../logreader.cpp \
           ../logsender.cpp
