######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 30 16:23:00 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h jfq.h
FORMS += jfq.ui
SOURCES += adder.cpp main.cpp
