######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 30 19:21:31 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h
FORMS += adder.ui
SOURCES += adder.cpp main.cpp
