######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 25 20:15:59 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first.cpp
