######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 25 21:10:50 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += textcode.cpp
